# Generated by Django 5.1.7 on 2025-03-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='date_start',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='date_renew',
            new_name='current_period_end',
        ),
    ]
