# Generated by Django 5.1.7 on 2025-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcategory',
            options={'ordering': ('is_sensitive', 'name')},
        ),
        migrations.AddField(
            model_name='qrcategory',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
