# Generated by Django 5.1.7 on 2025-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0002_alter_qrcategory_options_qrcategory_is_sensitive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField()),
                ('name', models.CharField(help_text='What is the event called?', max_length=128)),
                ('summary', models.CharField(help_text='What is the event description?', max_length=512)),
                ('start', models.DateTimeField(auto_now_add=True, help_text='When does the event begin?')),
                ('end', models.DateTimeField(auto_now_add=True, help_text='When does the event finish?')),
            ],
            options={
                'ordering': ('-start', 'name'),
            },
        ),
    ]
