# Generated by Django 5.1.7 on 2025-03-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0002_rename_date_start_stripesubscription_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='product',
        ),
        migrations.CreateModel(
            name='StripeSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=64)),
                ('price', models.ForeignKey(help_text='What Stripe Price is being mapped?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripeprice')),
            ],
            options={
                'ordering': ('stripe_id', 'price'),
            },
        ),
    ]
