# Generated by Django 5.1.7 on 2025-03-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0003_remove_stripesubscription_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionitem',
            name='subscription',
            field=models.ForeignKey(default=50, help_text='What Stripe Price is being mapped?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripesubscription'),
            preserve_default=False,
        ),
    ]
