# Generated by Django 5.1.7 on 2025-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start', 'summary')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', help_text='What is the event description?', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(help_text='What is the event summary?', max_length=512),
        ),
    ]
