# Generated by Django 5.1.7 on 2025-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0004_alter_event_options_remove_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='What is the event description?', max_length=2048),
        ),
    ]
