# Generated by Django 5.1.7 on 2025-03-23 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0005_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='Who is the person associated with this Docuseal submitter?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.event')),
                ('person', models.ForeignKey(help_text='Who is the person associated with this Docuseal submitter?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.person')),
            ],
            options={
                'ordering': ('person', 'event'),
            },
        ),
    ]
