# Generated by Django 5.1.7 on 2025-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0007_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('can_view_detail', 'Can view detailed user data'), ('can_view_status', 'Can tell if user is current'), ('can_search_people', 'Can search for people'), ('can_list_people', 'Can view people list'), ('can_remove_check_in', 'Can delete a check-in record'), ('can_refresh_data', 'Can force Docuseal and Stripe data to refresh')]},
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_order',
            field=models.IntegerField(default=1),
        ),
    ]
