# Generated by Django 5.1.7 on 2025-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0009_docusealsubmission_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusealsubmission',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
