# Generated by Django 5.1.7 on 2025-04-26 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0010_docusealsubmission_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personevent',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='personevent',
            options={},
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
