# Generated by Django 5.1.7 on 2025-04-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0011_remove_personevent_event_alter_personevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField()),
                ('recurrence_order', models.IntegerField(default=1)),
                ('summary', models.CharField(help_text='What is the event summary?', max_length=512)),
                ('description', models.TextField(help_text='What is the event description?', max_length=2048)),
                ('start', models.DateTimeField(help_text='When does the event begin?')),
                ('end', models.DateTimeField(help_text='When does the event finish?')),
            ],
            options={
                'ordering': ('-start', 'summary'),
            },
        ),
        migrations.AlterModelOptions(
            name='personevent',
            options={'ordering': ('person', 'event')},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='What is the event summary?', max_length=512)),
                ('description', models.TextField(help_text='What is the event description?', max_length=2048)),
                ('start', models.DateTimeField(help_text='When does the event begin?')),
                ('end', models.DateTimeField(help_text='When does the event finish?')),
                ('calendar_event', models.ForeignKey(blank=True, help_text='Which calendar event is this?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.calendarevent')),
            ],
            options={
                'ordering': ('-start', 'summary'),
            },
        ),
        migrations.AddField(
            model_name='personevent',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Who is the person associated with this Docuseal submitter?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='subwaive.event'),
        ),
    ]
