# Generated by Django 5.1.7 on 2025-04-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0012_calendarevent_alter_personevent_options_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personevent',
            name='event',
            field=models.ForeignKey(default=1, help_text='Who is the person associated with this Docuseal submitter?', on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='subwaive.event'),
            preserve_default=False,
        ),
    ]
