# Generated by Django 5.1.7 on 2025-07-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0013_alter_personevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentlink',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_event',
            field=models.ForeignKey(blank=True, help_text='Which calendar event is this?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subwaive.calendarevent'),
        ),
    ]
