# Generated by Django 5.1.7 on 2025-07-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0014_stripepaymentlink_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='StripeOneTimePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=64)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=64)),
                ('customer', models.ForeignKey(help_text='What Stripe Customer holds this Subscription?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripecustomer')),
                ('payment_link', models.ForeignKey(help_text='What Stripe Customer holds this Subscription?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripepaymentlink')),
            ],
            options={
                'ordering': ('stripe_id',),
            },
        ),
    ]
