# Generated by Django 5.1.7 on 2025-07-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0015_alter_stripecustomer_stripe_id_stripeonetimepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='stripe_id',
            field=models.CharField(max_length=128),
        ),
    ]
