# Generated by Django 5.1.7 on 2025-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0016_alter_stripeonetimepayment_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepaymentlink',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
