# Generated by Django 5.1.7 on 2025-07-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0017_stripepaymentlink_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
