# Generated by Django 5.1.7 on 2025-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0018_alter_stripeonetimepayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='logging_level',
            field=models.IntegerField(default=0, help_text='Python logging level, as integer'),
        ),
    ]
