# Generated by Django 5.1.7 on 2025-08-03 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0019_log_logging_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personevent',
            options={'ordering': ('-check_in_time', 'person', 'event')},
        ),
        migrations.AddField(
            model_name='personevent',
            name='check_in_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When was the check-in logged?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personevent',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Who is the person associated with this Docuseal submitter?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='subwaive.event'),
        ),
    ]
