# Generated by Django 5.1.7 on 2025-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0020_alter_personevent_options_personevent_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField()),
                ('confirmation_id', models.CharField(max_length=32)),
                ('nfc_id', models.CharField(max_length=32)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Has this NFC token been confirmed?')),
                ('person', models.ForeignKey(help_text='Who is the person associated with this Stipe customer?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.person')),
            ],
        ),
    ]
