# Generated by Django 5.1.7 on 2025-08-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0021_nfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfc',
            old_name='confirmation_id',
            new_name='activation_id',
        ),
        migrations.RemoveField(
            model_name='nfc',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='nfc',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Has this NFC token been activated?'),
        ),
    ]
