# Generated by Django 5.1.7 on 2025-08-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0022_rename_confirmation_id_nfc_activation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfc',
            name='UID',
            field=models.CharField(help_text='Concatenated string representation of decimal values of UID hex array', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Who is the person associated with this Stipe customer?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
    ]
