# Generated by Django 5.1.7 on 2025-08-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0023_alter_nfc_uid_alter_nfc_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfc',
            old_name='UID',
            new_name='uid',
        ),
    ]
