# Generated by Django 5.1.7 on 2025-09-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0024_rename_uid_nfc_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_nfc_admin',
            field=models.BooleanField(default=False, help_text='Is this person allowed to see NFC terminal config debrief?'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='What is your phone number?', max_length=10)),
                ('phone_id', models.CharField(max_length=32)),
                ('activation_id', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=False, help_text='Has this NFC token been activated?')),
                ('person', models.ForeignKey(blank=True, help_text='Who is the person associated with this Stipe customer?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.person')),
            ],
        ),
    ]
