# Generated by Django 5.1.7 on 2025-09-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0025_person_is_nfc_admin_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docusealsubmittersubmission',
            options={'ordering': ('submitter', 'submission')},
        ),
        migrations.RemoveField(
            model_name='docusealsubmittersubmission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='docusealsubmittersubmission',
            name='status',
        ),
        migrations.AlterField(
            model_name='docusealfieldstore',
            name='field',
            field=models.ForeignKey(blank=True, help_text='What is the name of the field being extracted?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.docusealfield'),
        ),
        migrations.AlterField(
            model_name='docusealfieldstore',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Which submission is being extracted from?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.docusealsubmission'),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When was this submission archived in Docuseal?', null=True),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When was this submission completed in Docuseal?', null=True),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='When was this submission created in Docuseal?', null=True),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='slug',
            field=models.CharField(help_text='What is the URL slug for this submission?', max_length=32),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='status',
            field=models.CharField(help_text='What is the Docuseal status of this submission?', max_length=16),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='submission_id',
            field=models.PositiveIntegerField(help_text='What is the Docuseal ID of this submission?'),
        ),
        migrations.AlterField(
            model_name='docusealsubmission',
            name='template',
            field=models.ForeignKey(blank=True, help_text='What template was used for this submission?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.docusealtemplate'),
        ),
        migrations.AlterField(
            model_name='docusealsubmitter',
            name='email',
            field=models.EmailField(help_text='What is the email address of this submitter?', max_length=254),
        ),
        migrations.AlterField(
            model_name='docusealsubmitter',
            name='slug',
            field=models.CharField(help_text='What is the URL slug for this submitter?', max_length=32),
        ),
        migrations.AlterField(
            model_name='docusealsubmitter',
            name='submitter_id',
            field=models.PositiveIntegerField(help_text='What is the Docuseal ID of this submitter?'),
        ),
        migrations.AlterField(
            model_name='docusealsubmittersubmission',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='What submission did this submitter submit?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.docusealsubmission'),
        ),
        migrations.AlterField(
            model_name='docusealsubmittersubmission',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='Who is the submitter for this submission?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.docusealsubmitter'),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='activation_id',
            field=models.CharField(help_text='URL secret used to activate this NFC.', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='nfc_id',
            field=models.CharField(help_text='URL secret used to register this NFC.', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Person associated with this NFC?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='uid',
            field=models.CharField(help_text='UID identifying this NFC', max_length=32),
        ),
    ]
