# Generated by Django 5.1.7 on 2025-09-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0026_alter_docusealsubmittersubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='UID',
            field=models.UUIDField(help_text='What is the ical UID of this calendar event?'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(help_text='What is the calendar event description?', max_length=2048),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(help_text='When does the calendar event finish?'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_order',
            field=models.IntegerField(default=1, help_text='What is the ical recurrence_order of this calendar event?'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(help_text='When does the calendar event begin?'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='summary',
            field=models.CharField(help_text='What is the calendar event summary?', max_length=512),
        ),
        migrations.AlterField(
            model_name='docusealtemplate',
            name='folder_name',
            field=models.CharField(help_text='What folder id this template under in Docuseal?', max_length=128),
        ),
        migrations.AlterField(
            model_name='docusealtemplate',
            name='name',
            field=models.CharField(help_text='What is the name of this template?', max_length=128),
        ),
        migrations.AlterField(
            model_name='docusealtemplate',
            name='slug',
            field=models.CharField(help_text='What is the URL slug for this template?', max_length=32),
        ),
        migrations.AlterField(
            model_name='docusealtemplate',
            name='template_id',
            field=models.PositiveIntegerField(help_text='What is the Docuseal ID of this template?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_event',
            field=models.ForeignKey(blank=True, help_text='Which calendar event is this based on?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subwaive.calendarevent'),
        ),
        migrations.AlterField(
            model_name='log',
            name='json',
            field=models.JSONField(blank=True, help_text='What JSON describes the event?', null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='logging_level',
            field=models.IntegerField(default=0, help_text='What is the Python logging level of the event?'),
        ),
        migrations.AlterField(
            model_name='log',
            name='other_info',
            field=models.TextField(blank=True, help_text='What additional detail helps describe the event?', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='activation_id',
            field=models.CharField(help_text='What is the URL secret used to activate this NFC token?', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='nfc_id',
            field=models.CharField(help_text='What is the URL secret used to register this NFC token?', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfc',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Person associated with this NFC token?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='What is the preferred name for ths person?', max_length=128),
        ),
        migrations.AlterField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(help_text='Who is the person associated with this email address?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='event',
            field=models.ForeignKey(blank=True, help_text='What event is associated with this check-in?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='subwaive.event'),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='person',
            field=models.ForeignKey(help_text='Who is the person checked-in to this event?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='activation_id',
            field=models.CharField(help_text='What is the URL secret used to activate this phone number?', max_length=32),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Has this phone number been activated?'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Who is the person associated with this phone number?', null=True, on_delete=django.db.models.deletion.CASCADE, to='subwaive.person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_id',
            field=models.CharField(help_text='What is the URL secret for registering this phone number?', max_length=32),
        ),
        migrations.AlterField(
            model_name='qrcategory',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Should this link be hidden from unauthenticated viewers?'),
        ),
        migrations.AlterField(
            model_name='qrcategory',
            name='name',
            field=models.CharField(help_text='What is the name of the QR code category?', max_length=64),
        ),
        migrations.AlterField(
            model_name='qrcustom',
            name='name',
            field=models.CharField(help_text='What is the name of the QR code?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='email',
            field=models.EmailField(help_text='What is the email address of this customer?', max_length=254),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(help_text='What is the name of this customer?', max_length=128),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='What is the Stripe ID of this customer?', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='customer',
            field=models.ForeignKey(help_text='What Stripe Customer is associated with this checkout session?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripecustomer'),
        ),
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='date',
            field=models.DateField(blank=True, help_text='What is date is associated with the payment link or what was the date the checkout session occurred?', null=True),
        ),
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='payment_link',
            field=models.ForeignKey(help_text='What payment link was used to initiate this checkout session?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripepaymentlink'),
        ),
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='status',
            field=models.CharField(help_text='What is the status of tis checkout session?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripeonetimepayment',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this checkout session?', max_length=128),
        ),
        migrations.AlterField(
            model_name='stripepaymentlink',
            name='date',
            field=models.DateField(blank=True, help_text='What event_date was provided in the payment link metadata?', null=True),
        ),
        migrations.AlterField(
            model_name='stripepaymentlink',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Is this payment link for a recurring charge?'),
        ),
        migrations.AlterField(
            model_name='stripepaymentlink',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this payment link?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripepaymentlink',
            name='url',
            field=models.URLField(help_text='What is the URL of this payment link?'),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='interval',
            field=models.CharField(help_text='What is the interval type of this price?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='price',
            field=models.IntegerField(help_text='What is the numerical base-currency value of this price?'),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this price?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='description',
            field=models.TextField(help_text='What is the description of this product?', max_length=512),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='name',
            field=models.CharField(help_text='What is the name of this product?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this product?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='created',
            field=models.DateTimeField(blank=True, help_text='When was this subscription created?', null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='When does this subscription end if not renewed?', null=True),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='name',
            field=models.CharField(help_text='What is the name of this subscription?', max_length=128),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='status',
            field=models.CharField(help_text='What is the status of this subscription?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this subscription?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionitem',
            name='price',
            field=models.ForeignKey(help_text='What Stripe Price is associated with the subscription item?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripeprice'),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionitem',
            name='stripe_id',
            field=models.CharField(help_text='What is the Stripe ID of this subscription item?', max_length=64),
        ),
        migrations.AlterField(
            model_name='stripesubscriptionitem',
            name='subscription',
            field=models.ForeignKey(help_text='What subscription is this subscription item a part of?', on_delete=django.db.models.deletion.CASCADE, to='subwaive.stripesubscription'),
        ),
    ]
