# Generated by Django 5.1.7 on 2025-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0027_alter_calendarevent_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='What is the secret token uniquely identifying this terminal?', max_length=128, unique=True)),
                ('location', models.CharField(help_text='Where is this terminal located? What are uses this terminal for check-ins?', max_length=128)),
            ],
            options={
                'ordering': ('location', 'token'),
            },
        ),
        migrations.AlterModelOptions(
            name='nfc',
            options={'ordering': ('person', 'uid', 'is_active')},
        ),
    ]
