# Generated by Django 5.1.7 on 2025-09-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0028_nfcterminal_alter_nfc_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_nfc_admin',
        ),
    ]
