# Generated by Django 5.1.7 on 2025-09-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subwaive', '0029_remove_person_is_nfc_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfc',
            old_name='nfc_id',
            new_name='registration_id',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='phone_id',
            new_name='registration_id',
        ),
    ]
