services:
  subwaive-db:
    image: postgres:17
    environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - subwaive

  subwaive:
    build: .
    container_name: subwaive
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
  
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - subwaive-db
    env_file:
      - .env
    networks:
      - subwaive
    volumes:
      - staticfiles:/app/subwaive/static
    restart: unless-stopped

  nginx:
     build: ./nginx
     volumes:
       - staticfiles:/app/subwaive/static
     ports:
       - 80:80
     image: nginx:django
     depends_on:
       - subwaive
     restart: "on-failure"
     networks:
       - subwaive

volumes:
   postgres_data:
   staticfiles:
networks:
  subwaive:
    external: true